name: Deploy to Netlify

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Build project
        run: npm run build --if-present

  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Link Netlify Site
        run: NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify link --id ${{ secrets.NETLIFY_SITE_ID }}
      
      - name: Netlify Build
        run: NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} netlify build

      - name: Deploy to Netlify
        run: netlify deploy --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
